services:
  bd:
    image: mysql:8.0
    restart: always
    container_name: bd
    environment:
      MYSQL_DATABASE:             zekretdb
      MYSQL_ROOT_PASSWORD:        ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  # back:
  #   image: jcabrera9409/zekret-back:latest
  #   restart: on-failure
  #   environment:
  #     DATASOURCE_BD:    jdbc:mysql://bd:3306/zekretdb
  #     USER_BD:          $USER_BD
  #     PASSWORD_BD:      $PASSWORD_BD
  #     JWT_SECRET_KEY:   $JWT_SECRET_KEY
  #   depends_on:
  #     - bd
  #   volumes:
  #     - ./zekret-back/files:/app/files:ro
  #     - ./zekret-back/logs:/app/logs

  # front:
  #   image: jcabrera9409/zekret-front:latest
  #   restart: on-failure
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - back
  #   volumes:
  #     - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro
