services:
  bd:
    image: mariadb:11.2-jammy
    restart: always
    container_name: bd
    environment:
      MYSQL_DATABASE:             zekretdb
      MYSQL_ROOT_PASSWORD:        ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    command: >
      --max-connections=50
      --innodb-buffer-pool-size=128M
      --innodb-log-file-size=32M
      --innodb-flush-method=O_DIRECT
      --innodb-flush-log-at-trx-commit=2
      --query-cache-size=0
      --query-cache-type=0
      --performance-schema=OFF
      --skip-name-resolve
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3

  back:
    image: jcabrera9409/zekret-back:latest
    restart: always
    container_name: back
    platform: linux/amd64
    environment:
      DATASOURCE_URL:          $DATASOURCE_URL
      USER_BD:                $MYSQL_USER
      PASSWORD_BD:            $MYSQL_PASSWORD
      JWT_PUBLIC_KEY_PATH:    $JWT_PUBLIC_KEY_PATH
      JWT_PRIVATE_KEY_PATH:   $JWT_PRIVATE_KEY_PATH
    depends_on:
      - bd
    ports:
      - "8080:8080"
    volumes:
      - ./privateKey.pem:/work/files/privateKey.pem:ro
      - ./publicKey.pem:/work/files/publicKey.pem:ro
      - ./logs:/work/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # front:
  #   image: jcabrera9409/zekret-front:latest
  #   restart: on-failure
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - back
  #   volumes:
  #     - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro
